### ISSUE TITLE
safe_mode is no longer working

### ISSUE THREAD

**Issue by adantart** [HelgeSverre/mistral#2]
In ChatCompletionRequest model, you have to change the 

```
#[MapName('safe_mode')]
```

by the new allowed value:
```
#[MapName('safe_prompt')]
```

since from Jan 11th, API is more restrict with unsupported parameters: https://docs.mistral.ai/platform/changelog/

**Comment by HelgeSverre** [comment]
Thanks for letting me know!

I have released a fix for this and published a new release here: 
https://github.com/HelgeSverre/mistral/releases/tag/v1.0.1
