### ISSUE TITLE
Allow to change curl's timeout

### ISSUE THREAD

**Issue by adantart** [HelgeSverre/mistral#3]
By default, Saloon uses Guzzle's default config and it has only 30 seconds

if request takes longer it fails:

```
Saloon \ Exceptions \ Request \ FatalRequestException
cURL error 28: Operation timed out after 30075 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.mistral.ai/v1/chat/completions
```

would it be possible to change this when you instance Saloon ?

I know how to "override" changing original sources, but I don't find when to change it in your package in a beautiful way ;-)

**Comment by HelgeSverre** [comment]
Good catch, will provide a fix later today.

**Comment by HelgeSverre** [comment]
Fixed in https://github.com/HelgeSverre/mistral/releases/tag/v1.0.2

**Comment by adantart** [comment]
Sorry to bother ... are you sure there's implementation of timeout ?
I see the "test/connectorTest", but not in the "real" requests.

I ask it because it's not working (after upgrading)

cURL error 28: Operation timed out after 30074 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.mistral.ai/v1/chat/completions

I tested with 
MISTRAL_TIMEOUT=120
MISTRAL_TIMEOUT=10000
MISTRAL_TIMEOUT=0
...

**Comment by HelgeSverre** [comment]
Did you republish the conigg file after upgrading?

lør. 27. jan. 2024, 19:32 skrev Alex ***@***.***>:

**Comment by adantart** [comment]
touché !
