### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by invaders-xx** [HelgeSverre/mistral#6]
Just migrated to Laravel 11 and this package is not compatible.

Any chance to have a L11 compatible version ?

Many thanks in advance

**Comment by HelgeSverre** [comment]
Just published, v1.3.0, see if that works for you.

**Comment by HelgeSverre** [comment]
nvm broke it, gimme 4 mins

**Comment by HelgeSverre** [comment]
there, v1.3.1, try that one.

**Comment by invaders-xx** [comment]
Thanks it works !
